const mongoose = require('mongoose');

const financialSnapshotResponseSchema = new mongoose.Schema({
  financialTitle:{ type: String, default: '' },
  financialSnapshot: { type: String, default: '' },
  fundingAsk: { type: String, default: '' },
  revenueChart: { type: String, default: '' },
  costChartValue: { type: String, default: '' },
  useOfFunds: { type: String, default: '' },
  revenue2019: { type: String, default: '' },
  revenue2020: { type: String, default: '' },
  revenue2021: { type: String, default: '' },
  revenue2022: { type: String, default: '' },
  revenue2023: { type: String, default: '' },
  revenue2024: { type: String, default: '' },
  revenue2025: { type: String, default: '' },
  revenue2026: { type: String, default: '' },
  revenue2027: { type: String, default: '' },
  revenue2028: { type: String, default: '' },
  cost2019: { type: String, default: '' },
  cost2020: { type: String, default: '' },
  cost2021: { type: String, default: '' },
  cost2022: { type: String, default: '' },
  cost2023: { type: String, default: '' },
  cost2024: { type: String, default: '' },
  cost2025: { type: String, default: '' },
  cost2026: { type: String, default: '' },
  cost2027: { type: String, default: '' },
  cost2028: { type: String, default: '' },
  productDevelopment: { type: String, default: '' },
  marketingSales: { type: String, default: '' },
  capex: { type: String, default: '' },
  businessOperations: { type: String, default: '' },
  teamSalaries: { type: String, default: '' }
});
module.exports = financialSnapshotResponseSchema;
