
const propertyToSchemaMap = {
    companyName: 'about',
    tagline: 'about',
    logo: 'about',
    primaryColor: 'about',
    secondaryColor: 'about',
    p50s50: 'about',
    p75s25: 'about',
    p25s75: 'about',
    establishmentYear: 'companyDetails',
    companyOverview: 'companyDetails',
    problemDescription: 'problemDescription',
    solutionsDescription: 'solutionDescription',
    sector: 'market',
    otherSector: 'market',
    marketDescription: 'market',
    TAM: 'market',
    TAMGrowthRate: 'market',
    SAM: 'market',
    SAMGrowthRate: 'market',
    productOverview: 'product',
    productRoadmap: 'product',
    productRoadmapDescription: 'product',
    technicalArchitecture: 'product',
    appType: 'productScreen',
    mobileScreenshots: 'productScreen',
    webScreenshots: 'productScreen',
    businessModel: 'businessModel',
    keyStakeholders: 'goToMarket',
    customerPersona: 'goToMarket',
    goToMarketStrategy: 'goToMarket',
    trackRecord: 'trackRecord',
    caseStudies: 'caseStudies',
    testimonials: 'testimonials',
    competitors: 'competitors',
    competitiveDiff: 'competitiveDiff',
    teamMembers: 'teamMembers',
    websiteLink: 'contactInfo',
    linkedinLink: 'contactInfo',
    contactEmail: 'contactInfo',
    contactPhone: 'contactInfo',
    financialSnapshot: 'financialInfo',
    revenueCost:'financialInfo',
    plannedRaise: 'financialInfo',
    useOfFunds: 'financialInfo',
    percentage: 'financialInfo'
  };
  
module.exports = propertyToSchemaMap;
  