const sectionToUrlMap1 = {
  about:
    "https://script.google.com/macros/s/AKfycbz9rrvDN2L7f4_6IN6DC9dyf8xu9XVQKG4QN3Xlu9Edr6qz5qN8NhL4ohFsiqZm9aEF/exec",
  companyDetails:
    "https://script.google.com/macros/s/AKfycbxaKNul5asrp-tluP7oZDx1xIzAFRKq4g90kJzqe6kWyptYyd71AwCiDrtjd9954hVs/exec",
  problemDescription:
    "https://script.google.com/macros/s/AKfycbynzaQbJ706KlOvs2_dekttSY19Ld2Lhl7J74MnDuN1lU8jyzxRJ9CpdB7bA1fnfPq2/exec",
  solutionDescription:
    "https://script.google.com/macros/s/AKfycbzd3GV8Xq8WYgpeuoBVQaRZLfRFifWR0DjiIuubbAdHlJAn6_Ik0Mp5wijxGbKWIhRD/exec",
  market:
    "https://script.google.com/macros/s/AKfycbzAv7x-2vk5hfZlVSqn9OQAB4ckpDAYJDq2AYSLwCAPpMmoxqTsi3wKSgoY1lg1rAej5A/exec",
  product:
    "https://script.google.com/macros/s/AKfycbzQI6dwEqp9hWd32SEk6qv3mNbTBSFxHvG824DLw2ZCKMQB0HWG4LxHCfsZ1Pj5LojG-g/exec",
  productScreen:
    "https://script.google.com/macros/s/AKfycbzaBrPT8XwK6sHQKxugZ9q5YOYDFI93Z-xA2ZlKHPfU118xycpBkDg3uzCSTCdu7wG-/exec",
  businessModel:
    "https://script.google.com/macros/s/AKfycbwII2lHge_tjbqIirO8JXCP9rNlQrw4oB4g3SjPWUG7e7KrI_LyXS3bRpkVPoeNREAa3Q/exec",
  goToMarket:
    "https://script.google.com/macros/s/AKfycbxiWP3ZFNwY1rwNvmh8qc4Ezu3_M3SuO-6Swwp_7Mi7tHOpNR3gpXVOuSwm3kslqYNHLA/exec",
  trackRecord:
    "https://script.google.com/macros/s/AKfycbzG0Zsg7PBjfj3irT7O1dlEr-WIjlyZhF6KKY7Bd3IyC5GMUjSS52FjgTepMYtAMfmFbw/exec",
  caseStudies:
    "https://script.google.com/macros/s/AKfycbyJOhF3K0HKtsQJ-WDABSGrfL5kC6XWop2c2I7XzPnLCThhlvOgWS_4reNBPvOevZ1GHA/exec",
  testimonials:
    "https://script.google.com/macros/s/AKfycbyKTWDez3_H6AAW3eHxKl_Fl4UViXOlM6DpJNytd70OppNmqhhJqGojrvJp_sEb5VTk/exec",
  competitors:
    "https://script.google.com/macros/s/AKfycbwZoMWD1Iak8-Xg083T4JzI4dQhrOc6lrbiU2ZF_wteEhwd2vIG46WxxG_oMswz81HWQA/exec",
  competitiveDiff:
    "https://script.google.com/macros/s/AKfycbycVQbkwwUYy-2-dckW1XjdFpg8V62vNQ-1dywJDCsvwJXdPiZaMECN497BmQxqsePKSA/exec",
  teamMembers:
    "https://script.google.com/macros/s/AKfycbyOn8kImNdU_s4UQzExvM5fakJQ_YY3fPov9ONASCBgxqIdgFqD_b6azXpul0rJ0bs4vQ/exec",
  financialInfo:
    "https://script.google.com/macros/s/AKfycbxFwI8nY6dPr6Pk8FtsMTFcjNA7UQ6OSXHEwI3J0v8bGzHpq-2wmHh3CJ-JA66gXe9NPg/exec",
  contactInfo:
    "https://script.google.com/macros/s/AKfycbwL9Nzvh7ilBf3_6Q-Jkp0e0c9cNkZS0GivgCdqingwdzV0H7eus63uH8lMnH6DPDnnBQ/exec",
};
module.exports = sectionToUrlMap1;