const sectionToUrlMap1 = {
  about:
    "https://script.google.com/macros/s/AKfycbyn-eS2ellyMrY1pxHeAcdexYmL0ZNDIUOoGKVmSRtzeDIgE7jcWL-4J-8sPHDaVp1H/exec",
  companyDetails:
    "https://script.google.com/macros/s/AKfycbxaKNul5asrp-tluP7oZDx1xIzAFRKq4g90kJzqe6kWyptYyd71AwCiDrtjd9954hVs/exec",
  problemDescription:
    "https://script.google.com/macros/s/AKfycby8-yhCoj_77PuwWZZPqoqeB73DxdVCtniMDuXdU3CJ9-Yhwyv_sq7K8_C1kjfgHaHu/exec",
  solutionDescription:
    "https://script.google.com/macros/s/AKfycbyfZsbIGrO0_0PAZH0dxnThjE8s0YL1Nv9qEnCVDCuV3ydn-Ooqw23upOES-L455KF_/exec",
  market:
    "https://script.google.com/macros/s/AKfycbzta6NNbk_oJXbG-f3Im6FKc4JA2-Pw40lzoyPt34cWZZCvU-6hfvRQnXWWla_pAsHmcQ/exec",
  product:
    "https://script.google.com/macros/s/AKfycbyiFCm_aTv98D8_tG4g95bRoLdvtUbqs8A0-lXZAaSxq0dawphX_znNbRYEaeTAg6kzsg/exec",
  productScreen:
    "https://script.google.com/macros/s/AKfycbzi5sDeDUK7H2Cz4nTpTiQ_yxePFblskVovURQVnCwnTWk0gWzn_qsZyRnDzWcNwBEg/exec",
  businessModel:
    "https://script.google.com/macros/s/AKfycbxP3uDcD_dkRK-JWj0Lh3cOs1QovmmQXaOCPrNLSwHGShOBGMFSMSC02JGlSZtCOhsZxQ/exec",
  goToMarket:
    "https://script.google.com/macros/s/AKfycbyRtel7GBrymMc_ml9ofp_XqtGY9dajV6sbT0rXsinwJYRgznolOm-EXVpSo6euhj_82A/exec",
  trackRecord:
    "https://script.google.com/macros/s/AKfycbwpU7iD6MrXqjIBVOmieKyDQbYcS7IpMI2zCe7Q6GxhgEigCNky9K33T2yyIOlBCL4Q7A/exec",
  caseStudies:
    "https://script.google.com/macros/s/AKfycbwQCOj9fm9JrAbYB0jKS_oVF7vOUKy7YM6MjFPPDm5AuCcOdwMtuReDq3xubfL9FWC6fw/exec",
  testimonials:
    "https://script.google.com/macros/s/AKfycbwNvDBqWU-yXWNrVxj5b0n-8ljO2mqkm-VX1WqPtNCpTdhTqjbWczWW0MvqOBM7rxje/exec",
  competitors:
    "https://script.google.com/macros/s/AKfycbx1bKZT8J53aLQfHd1BfNGMK5SEDvWPByi89YBNf6PjupqlAm3AGjUpcrSfJBa-Kh8g4Q/exec",
  competitiveDiff:
    "https://script.google.com/macros/s/AKfycbxPw7jeVBwYRponUA20Vonc7Ge-iXebuH4UpV-L1LHn9p8LY9e7uoS3RXJbFdgPhfbtlA/exec",
  teamMembers:
    "https://script.google.com/macros/s/AKfycbza2K_DHjJ_PsyhhlPK8x4V9yNRAJ14xpm8oQ4HnSOYcBRuu6F9Vf3wkS3JwW-8fac3gQ/exec",
  financialInfo:
    "https://script.google.com/macros/s/AKfycby83p12aA6bOPAUjcVIt4PKlHd6SdH34Nz8Fuh_nbBqG-lo6zSZyK3rPiImcMxtEoSqMA/exec",
  contactInfo:
    "https://script.google.com/macros/s/AKfycbz7OLnaE2t9vCv7DHuC-zpGoTlQ8erILKc0AjKQkXHnSd9pdJ79Ih71mN8yehODO3IjkA/exec",
};
module.exports = sectionToUrlMap1;