const sectionToUrlMap1 = {
  about:
    "https://script.google.com/macros/s/AKfycbxs-sTPw9uc0XG2c_ChSUZVAV6kWyeM5txhxnRssr9jzUgJWoOg662yh3UAHndne6nl/exec",
  companyDetails:
    "https://script.google.com/macros/s/AKfycbxnG--d2jnMhdFRi5GvGot0aX8bfXKk8FRgFYRaXKunGFw8mCN_tQ8vfDxjxqPuQk4Y/exec",
  problemDescription:
    "https://script.google.com/macros/s/AKfycbzFO8T05oX82HVxCErGWlLyBN_Sy4ILo6a2sYvdqRtRCOdhmGIALEb29yTkbhgnEAX2/exec",
  solutionDescription:
    "https://script.google.com/macros/s/AKfycbyyabH_q2KQ3j9Vk8MWhyT9ehifvNWEw2WnCnreKb8rIAH6KRQLIZ5kyT6hlpBRmO38/exec",
  market:
    "https://script.google.com/macros/s/AKfycbzWxRvwpJlIXgTTdt4pq0dMq3T4xeThLwKsO7uRw5G72hBT35Ss3g-h4XuJeGDSqx5RAQ/exec",
  product:
    "https://script.google.com/macros/s/AKfycbzniY1_wxBYEPxzUpVsbgMADty8HFPFuzsjV7lb1gEXERyDneSLX-25NmVh0yvwYYfhtA/exec",
  productScreen:
    "https://script.google.com/macros/s/AKfycbxHWlI8iPNABHL1RpmWZL1rWkI4PgzdVGE72H1HsIziHRwxl0APV6ZChi_FX4q5v0XF/exec",
  businessModel:
    "https://script.google.com/macros/s/AKfycbwTiBDRDRcwXIM_hyr5xQrfLrkrE57bMM-sGZThdS_uc8r1KnPvvLqDcz3VXfTtU8dFtQ/exec",
  goToMarket:
    "https://script.google.com/macros/s/AKfycbwTvkJeHCIPvor5kToqIlNbNVG6R4CPDkAKvv0cXflaopsuOnbYHFNOUv3ZKcaj4_9kNg/exec",
  trackRecord:
    "https://script.google.com/macros/s/AKfycbwMRKxI-1nd55dAX2Jw5cEGJvwyrNF-7ATC6eVoKwfwxnEu7WtR-hKzAJ1yV-xuO82Z4Q/exec",
  caseStudies:
    "https://script.google.com/macros/s/AKfycbzOZEgZUVLaguo-K11Deu4E05ugD35bwNACXclqCYCqvS7ie3iNrn7b9mymXx9XThcvrw/exec",
  testimonials:
    "https://script.google.com/macros/s/AKfycbyLcjAZix7oqH8xQzx1qiiuF2y3GFfdCRi0piPZehKw3OLPThJh8IL1NjqNQ7qIssUG/exec",
  competitors:
    "https://script.google.com/macros/s/AKfycbxY9goQyvwizEoEkvCI7aagyCmuFK8r-3p90vWOWGNkmMq2dzxVZkCrd0Bw7010kqDy4Q/exec",
  competitiveDiff:
    "https://script.google.com/macros/s/AKfycbyKunOMMwzlb9zmxCjWoo3uNnv1ZomRppqGLbtWhALQw3qxxC5wfUmHOgASVGYiIlzS4g/exec",
  teamMembers:
    "https://script.google.com/macros/s/AKfycbz68yvPUPfqUzX7k_WYWPC0iPR9QFgWplKUtO_SAbeXYiEUYcP0e5OiJ5xMG3addf80Tw/exec",
  financialInfo:
    "https://script.google.com/macros/s/AKfycbyKmI_T3gMZ3ESyBBsQJpJc2pKL4NCICSNBf72xJE-a8JZzeRBjCzKnXUMm6J3LIdGBTw/exec",
  contactInfo:
    "https://script.google.com/macros/s/AKfycbxW8u8sJ_8coc2-ZBsdQLTWxidagPmXO4PvlCQTW-FqrHHd7emLcJnYmXkOO9duTeQS-Q/exec",
};
module.exports = sectionToUrlMap1;